// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WashingAPI.DBModels
{
    [Table("login")]
    [Index(nameof(GoogleId), Name = "UQ__login__0DA2E482E849BD18", IsUnique = true)]
    public partial class Login
    {
        [Key]
        [Column("googleId")]
        [StringLength(255)]
        public string GoogleId { get; set; }
        [Required]
        [Column("fornavn")]
        [StringLength(255)]
        public string Fornavn { get; set; }
        [Required]
        [Column("efternavn")]
        [StringLength(255)]
        public string Efternavn { get; set; }
        [Required]
        [Column("room")]
        [StringLength(20)]
        public string Room { get; set; }
    }
}