// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WashingAPI.DBModels
{
    [Table("loginRequest")]
    [Index(nameof(GoogleId), Name = "UQ__loginReq__0DA2E4827C9B5337", IsUnique = true)]
    public partial class LoginRequest
    {
        [Key]
        [Column("googleId")]
        [StringLength(255)]
        public string GoogleId { get; set; }
        [Required]
        [Column("fornavn")]
        [StringLength(255)]
        public string Fornavn { get; set; }
        [Required]
        [Column("efternavn")]
        [StringLength(255)]
        public string Efternavn { get; set; }
        [Required]
        [Column("room")]
        [StringLength(20)]
        public string Room { get; set; }
    }
}